library(datasets)
data("mtcars")
summary(mtcars)
plot(mpg~wt,data = mtcars)
lm.mtcars=lm(mpg~wt,data = mtcars)
abline(lm.mtcars,lwd=2,col=2)
summary(lm.mtcars)
qt(.975,28)
hist(lm.mtcars$residuals)
qqnorm(lm.mtcars$residuals)
qqline(lm.mtcars$residuals)
plot(lm.mtcars$residuals)
abline(h=0,col="red")
shapiro.test(lm.mtcars$residuals)
lm.mpg <- step(lm(mpg ~ ., data = mtcars))
summary(lm.mpg)