library(HSAUR)
data("skulls")
attach(skulls)
summary(skulls)
sk.mod = lm(cbind(mb, bh, bl, nh) ~ epoch, data = skulls)
summary(sk.mod)
m.sk.mod = manova(sk.mod)
summary(m.sk.mod)
summary.aov(m.sk.mod)
